image: php:7.2

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - docker-php-ext-install pcntl
          - pecl install mongodb && docker-php-ext-enable mongodb
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer install
          - vendor/bin/phpunit
        services:
          - mongo

definitions:
  services:
    mongo:
      image: mongo