image: butschster/php7.2-mongo

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - composer install
          - export APP_KEY=base64:WRUogOMEhBVViMNAd/W5ArqS0bnXz2X/+NKylASkHk8=
          - export APP_URL=http://localhost
          - php artisan key:generate
          - vendor/bin/phpunit
        services:
          - mongo

definitions:
  services:
    mongo:
      image: mongo