image: butschster/php7.2-mongo

pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - apt-get update && apt-get install -y unzip
          - composer install
          - php -r \"copy('.env.example', '.env');\"
          - php artisan key:generate
          - vendor/bin/phpunit
        services:
          - mongo

definitions:
  services:
    mongo:
      image: mongo