    var Ziggy = {
        namedRoutes: {"api.":{"uri":"api\/video\/{video}\/comments\/cache","methods":["DELETE"],"domain":null},"api.auth.register":{"uri":"api\/register","methods":["POST"],"domain":null},"api.auth.permissions":{"uri":"api\/me\/permissions","methods":["GET","HEAD"],"domain":null},"api.auth.me":{"uri":"api\/me","methods":["GET","HEAD"],"domain":null},"api.channel.metrics":{"uri":"api\/channel\/{channel}\/metrics","methods":["GET","HEAD"],"domain":null},"api.channel.comments.spam":{"uri":"api\/channel\/{channel}\/comments\/spam","methods":["GET","HEAD"],"domain":null},"api.channel.comments":{"uri":"api\/channel\/{channel}\/comments","methods":["GET","HEAD"],"domain":null},"api.channels.reported":{"uri":"api\/channel\/reported","methods":["GET","HEAD"],"domain":null},"api.channels.bots":{"uri":"api\/channel\/bots","methods":["GET","HEAD"],"domain":null},"api.channels.followed":{"uri":"api\/channels\/followed","methods":["GET","HEAD"],"domain":null},"api.channel.videos":{"uri":"api\/channel\/{channel}\/videos","methods":["GET","HEAD"],"domain":null},"api.channel.show":{"uri":"api\/channel\/{channel}","methods":["GET","HEAD"],"domain":null},"api.channel.check":{"uri":"api\/channel\/check","methods":["POST"],"domain":null},"api.channel.report":{"uri":"api\/channel\/report","methods":["POST"],"domain":null},"api.channel.moderate":{"uri":"api\/channel\/{channel}\/moderate","methods":["POST"],"domain":null},"api.comment.metrics":{"uri":"api\/comment\/{comment}\/metrics","methods":["GET","HEAD"],"domain":null},"api.comment.show":{"uri":"api\/comment\/{comment}","methods":["GET","HEAD"],"domain":null},"api.video.metrics":{"uri":"api\/video\/{video}\/metrics","methods":["GET","HEAD"],"domain":null},"api.video.comments.spam":{"uri":"api\/video\/{video}\/comments\/spam","methods":["GET","HEAD"],"domain":null},"api.video.comments":{"uri":"api\/video\/{video}\/comments","methods":["GET","HEAD"],"domain":null},"api.videos":{"uri":"api\/videos","methods":["GET","HEAD"],"domain":null},"api.video.tags":{"uri":"api\/video\/{video}\/tags","methods":["GET","HEAD"],"domain":null},"api.video.show":{"uri":"api\/video\/{video}","methods":["GET","HEAD"],"domain":null},"api.tag.videos":{"uri":"api\/tag\/{tag}\/videos","methods":["GET","HEAD"],"domain":null},"api.tag.show":{"uri":"api\/tag\/{tag}","methods":["GET","HEAD"],"domain":null},"channel.created.date":{"uri":"channels\/created\/{date}","methods":["GET","HEAD"],"domain":null},"channel.bots.date":{"uri":"bots\/created\/{date}","methods":["GET","HEAD"],"domain":null},"channel.bots":{"uri":"bots\/grouped-by-date","methods":["GET","HEAD"],"domain":null},"comments.spam":{"uri":"comments\/spam","methods":["GET","HEAD"],"domain":null}},
        baseUrl: 'http://localhost/',
        baseProtocol: 'http',
        baseDomain: 'localhost',
        basePort: false,
        defaultParameters: []
    };

    export {
        Ziggy
    }
